name: Analytics Server

concurrency:
  group: analytics
  cancel-in-progress: true

on:
  push:
    tags:
      - '*standardnotes/analytics*'
  workflow_dispatch:

jobs:
  call_server_application_workflow:
    name: Server Application
    uses: ./.github/workflows/common-server-application.yml
    with:
      service_name: analytics
      workspace_name: "@standardnotes/analytics"
      deploy_web: false
      package_path: packages/analytics
    secrets: inherit
