name: Reusable Publish Docker Image Workflow

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      package_path:
        required: true
        type: string
      workspace_name:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache build
      id: cache-build
      uses: actions/cache@v4
      with:
        path: |
          packages/**/dist
        key: ${{ runner.os }}-${{ inputs.service_name }}-build-${{ github.sha }}

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: yarn install --immutable

    - name: Build
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: yarn build

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Publish Docker image
      uses: docker/build-push-action@v6
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ${{ inputs.package_path }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          standardnotes/${{ inputs.service_name }}:latest
          standardnotes/${{ inputs.service_name }}:${{ github.sha }}
