name: Publish Packages

on:
  push:
    branches: [ main ]

permissions:
  id-token: write

jobs:
  build-and-test:
    if: contains(github.event.head_commit.message, 'chore(release)') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache build
      id: cache-build
      uses: actions/cache@v4
      with:
        path: |
          packages/**/dist
        key: ${{ runner.os }}-build-${{ github.sha }}

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version-file: '.nvmrc'

    - name: Install
      run: yarn install --immutable

    - name: Build
      run: yarn build

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test

  e2e-base:
    needs: build-and-test
    name: E2E Base Suite
    uses: ./.github/workflows/common-e2e.yml
    with:
      snjs_image_tag: 'latest'
      suite: 'base'

  e2e-vaults:
    needs: build-and-test
    name: E2E Vaults Suite
    uses: ./.github/workflows/common-e2e.yml
    with:
      snjs_image_tag: 'latest'
      suite: 'vaults'

  publish-self-hosting:
    needs: [ e2e-base, e2e-vaults ]
    name: Publish Self Hosting Docker Image
    uses: ./.github/workflows/common-self-hosting.yml
    secrets: inherit
